### ISSUE TITLE
Update repo with more information

### ISSUE THREAD

**Issue by amingilani** [nodeschool/Lahore#1]
@usmantahirr, are you still organizing this?

**Comment by usmantahirr** [comment]
Yes I am, we are working on its website, FB Page and searching for sponcers, you will very soon see is activities. Moreover in Febuary, Google Developers Group is Planning a 5 weeks crash course on Android 101, I am waiting for confirmed dates of that, so that my dates won't conflict with it. Hang on and sit tight, you will see NodeSchool active in Lahore within a Month or so.

**Comment by amingilani** [comment]
Oh, perfect. Keep this issue open until you get the site up, though!

**Comment by usmantahirr** [comment]
Sure, its done. We are working on site and FB Page content BTW. I will share link in description.

**Comment by rashidshafique** [comment]
do we have an update on this ?
