### ISSUE TITLE
Nodeschool events in Lahore

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/Lahore#5]
Hey @usmantahirr,

I just had a private Gitter chat with @abdulhannanali and want to take the opportunity to approach you too.

I understand @abdulhannanali would like to run a coding event that incorporates Nodeschool materials amongst other coding languages and practices, which is being prevented?  

Is this the case?

@abdulhannanali - please add the points you raised to me privately as part of this issue.  Everything needs to be public.

Thanks

**Comment by usmantahirr** [comment]
Hello @iancrowther 
I already had a talk with @abdulhannanali. I prevented him because he scheduled an event as International day without even asking or notifying me when I was already making arrangements and talking to venders for International Day. Being chapter owner I think Its my responsibility to manage brand representation in Lahore.

I stopped @abdulhannanali because there was an event already being scheduled and he was overruling it without any notification or discussion.

After having discussion with him I asked him to discuss any event plan with me before doing any such thing. I just told him that I would never halt/stop her from doing anything. I'll just make sure everything done is in right way and is not affecting NodeSchool brand image in any way.

I'll be glad to work with him, but instead of overruling like this, he need to contact me so that I can add him to chapter contributors and he can officially do things and I am very open in helping everyone who approach me. But he have to do it properly.

Having same event, same day, in same city at 2 different places and 2 different teams will confuse audience and prevent people from trusting us.

I tried to convince @abdulhannanali in it. I hope he understands my point.
